```{r}
library(readr)
library(eulerr)
```

```{r}
#all organs
metabolites_by_organ <- read_csv("../data/metabolites_by_organ.csv")
```

```{r}
plot(venn(metabolites_by_organ[c("parotid","SMG",  "SLG","RPG")]))
```

```{r}
sessionInfo()
```

```
Warning: package ‘eulerr’ was built under R version 4.3.3
Show in New Window
Rows: 99 Columns: 7── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): id
lgl (6): RPG, SLG, SMG, pancreas, parotid, spleen
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Show in New Window

Show in New Window
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 26.6.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] eulerr_7.0.2 readr_2.1.5 

loaded via a namespace (and not attached):
 [1] bit_4.6.0          gtable_0.3.6       crayon_1.5.3       dplyr_1.1.4        compiler_4.3.1     tidyselect_1.2.1   Rcpp_1.1.0         parallel_4.3.1    
 [9] gridExtra_2.3      scales_1.4.0       yaml_2.3.10        fastmap_1.2.0      ggplot2_3.5.2      R6_2.6.1           generics_0.1.4     patchwork_1.3.1   
[17] knitr_1.50         viridis_0.6.5      forcats_1.0.0      polyclip_1.10-7    tibble_3.3.0       polylabelr_0.3.0   pillar_1.11.0      RColorBrewer_1.1-3
[25] tzdb_0.5.0         rlang_1.1.6        xfun_0.52          bit64_4.6.0-1      viridisLite_0.4.2  cli_3.6.5          magrittr_2.0.3     digest_0.6.37     
[33] grid_4.3.1         vroom_1.6.5        rstudioapi_0.17.1  hms_1.1.3          lifecycle_1.0.4    vctrs_0.6.5        pheatmap_1.0.13    evaluate_1.0.4    
[41] glue_1.8.0         farver_2.1.2       rmarkdown_2.29     tools_4.3.1        pkgconfig_2.0.3    htmltools_0.5.8.1 
```